version: "3.9"

services:
  db:
    image: library/postgres:13
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "${POSTGRES_PORT}:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "${AMQP_PORT}:5672"
      - "${AMQP_UI_PORT}:15672"